### ISSUE TITLE
Railgun Siege weapon changes

### ISSUE THREAD

**Issue by Qktay** [Xiaminou/HardcoreEmpires#41] opened 2018-07-31 18:15 UTC
"Heat" "7" //heat added per shot fired (100 total heat added to vehicle puts it in an overheated status).
                               Buffing the heat output because of the high fire rate
"Heat" "5" //heat added per shot fired (100 total heat added to vehicle puts it in an overheated status).

**Comment by Xiaminou** [comment] 2018-09-30 16:44
duplicate of #40

**Closed by Xiaminou** 2018-09-30 16:44 UTC
